$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$sourceFiles = @(
    'data/movie_data.dart',
    'data/genre_data.dart',
    'screens/genre_screen.dart',
    'main.dart'
)
$parts = @(
    '// Generated by tools/update_dartpad.ps1. Edit lib/ and regenerate this file.',
    "import 'package:flutter/material.dart';",
    ''
)
foreach ($sourceFile in $sourceFiles) {
    $source = Get-Content -LiteralPath (Join-Path $projectRoot "lib/$sourceFile") -Encoding utf8
    $parts += "// Source: lib/$sourceFile"
    $parts += $source | Where-Object { $_ -notmatch '^import ' }
    $parts += ''
}
$outputDirectory = Join-Path $projectRoot 'dartpad'
New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
Set-Content -LiteralPath (Join-Path $outputDirectory 'main.dart') -Value $parts -Encoding utf8
