// Generated by tools/update_dartpad.ps1. Edit lib/ and regenerate this file.
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// Source: lib/models/movieData.dart
class Trailer {
  const Trailer({
    required this.title,
    required this.duration,
    required this.description,
  });
  final String title;
  final String duration;
  final String description;
}

// The whole Movie object is passed to the detail screen through its constructor.
class Movie {
  const Movie({
    required this.id,
    required this.title,
    required this.posterUrl,
    required this.overview,
    required this.genres,
    required this.rating,
    required this.trailers,
    required this.year,
    required this.runtime,
  });
  final String id;
  final String title;
  final String posterUrl;
  final String overview;
  final List<String> genres;
  final double rating;
  final List<Trailer> trailers;
  final int year;
  final String runtime;
}

// Source: lib/data/dataMain.dart

// Static sample data only. Poster images use fixed URLs; no API calls.
const sampleMovies = <Movie>[
  Movie(
    id: 'inception',
    title: 'Inception',
    posterUrl:
        'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    overview:
        'Dom Cobb is a skilled thief who enters dreams to steal secrets. '
        'Offered a chance to return to his family, he accepts an unusual mission: '
        'plant an idea instead of stealing one. His team must navigate layers '
        'of dreams while his own memories threaten the entire operation.',
    genres: ['Science Fiction', 'Action', 'Thriller'],
    rating: 8.8,
    year: 2010,
    runtime: '2h 28m',
    trailers: [
      Trailer(
        title: 'Official Trailer',
        duration: '2:28',
        description:
            'Meet Cobb and discover a world where dreams can be shared.',
      ),
      Trailer(
        title: 'Behind the Dreams',
        duration: '1:45',
        description:
            'A sample behind-the-scenes entry about the dream-layer concept.',
      ),
    ],
  ),
  Movie(
    id: 'interstellar',
    title: 'Interstellar',
    posterUrl:
        'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    overview:
        'As Earth becomes increasingly difficult to inhabit, former pilot '
        'Cooper joins a mission through a mysterious wormhole. He and a team '
        'of scientists search for a new home for humanity, facing the limits '
        'of time, distance, and the bond between a father and his daughter.',
    genres: ['Adventure', 'Drama', 'Science Fiction'],
    rating: 8.7,
    year: 2014,
    runtime: '2h 49m',
    trailers: [
      Trailer(
        title: 'Official Trailer',
        duration: '2:19',
        description: 'A first look at the journey beyond our solar system.',
      ),
      Trailer(
        title: 'Space Exploration Featurette',
        duration: '3:10',
        description:
            'A sample featurette entry about the worlds visited by the crew.',
      ),
    ],
  ),
  Movie(
    id: 'spirited-away',
    title: 'Spirited Away',
    posterUrl:
        'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    overview:
        'Young Chihiro wanders into a mysterious spirit world while moving '
        'to a new town with her parents. To rescue her family, she takes a job '
        'at a magical bathhouse and learns to face fear with kindness, courage, '
        'and help from unexpected friends.',
    genres: ['Animation', 'Fantasy', 'Adventure'],
    rating: 8.6,
    year: 2001,
    runtime: '2h 5m',
    trailers: [
      Trailer(
        title: 'Official Trailer',
        duration: '2:04',
        description:
            'Enter the bathhouse and meet the spirits of Chihiro\'s adventure.',
      ),
      Trailer(
        title: 'A Magical World',
        duration: '1:32',
        description:
            'A sample teaser entry introducing the colorful fantasy setting.',
      ),
    ],
  ),
];

// Source: lib/state/movieState.dart

// Shared in-memory state survives Navigator.pop but resets on app restart.
class MovieLibrary extends ChangeNotifier {
  final Set<String> _favorites = {};
  final Map<String, int> _ratings = {};
  bool isFavorite(String id) => _favorites.contains(id);
  int? ratingFor(String id) => _ratings[id];
  int get favoriteCount => _favorites.length;

  void toggleFavorite(String id) {
    if (!_favorites.remove(id)) _favorites.add(id);
    notifyListeners();
  }

  void rate(String id, int rating) {
    assert(rating >= 1 && rating <= 10);
    _ratings[id] = rating;
    notifyListeners();
  }
}

// Source: lib/widgets/movie_poster.dart

class MoviePoster extends StatelessWidget {
  const MoviePoster({super.key, required this.movie, this.hero = false});
  final Movie movie;
  final bool hero;

  @override
  Widget build(BuildContext context) {
    final image = ClipRRect(
      borderRadius: BorderRadius.circular(14),
      child: Image.network(
        movie.posterUrl,
        fit: BoxFit.cover,
        width: double.infinity,
        height: double.infinity,
        semanticLabel: '${movie.title} poster',
        loadingBuilder: (context, child, progress) => progress == null
            ? child
            : const ColoredBox(
                color: Color(0xFF303849),
                child: Center(child: CircularProgressIndicator(strokeWidth: 2)),
              ),
        errorBuilder: (context, error, stackTrace) => const ColoredBox(
          color: Color(0xFF303849),
          child: Center(child: Icon(Icons.movie_outlined, size: 44)),
        ),
      ),
    );
    return hero ? Hero(tag: 'poster-${movie.id}', child: image) : image;
  }
}

// Source: lib/screens/movieDetail.dart

class MovieDetailScreen extends StatelessWidget {
  const MovieDetailScreen({
    super.key,
    required this.movie,
    required this.library,
  });
  final Movie movie;
  final MovieLibrary library;

  Future<void> _rateMovie(BuildContext context) async {
    var selected = library.ratingFor(movie.id) ?? 8;
    final rating = await showDialog<int>(
      context: context,
      builder: (context) => StatefulBuilder(
        builder: (context, setDialogState) => AlertDialog(
          title: Text('Rate ${movie.title}'),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                '$selected / 10',
                style: Theme.of(context).textTheme.headlineMedium,
              ),
              Slider(
                value: selected.toDouble(),
                min: 1,
                max: 10,
                divisions: 9,
                label: '$selected',
                onChanged: (value) =>
                    setDialogState(() => selected = value.round()),
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Cancel'),
            ),
            FilledButton(
              onPressed: () => Navigator.pop(context, selected),
              child: const Text('Save rating'),
            ),
          ],
        ),
      ),
    );
    if (rating != null) library.rate(movie.id, rating);
  }

  Future<void> _shareMovie(BuildContext context) async {
    final text =
        '${movie.title} (${movie.year})\nRating: ${movie.rating.toStringAsFixed(1)}/10\n'
        'Genres: ${movie.genres.join(', ')}\n\n${movie.overview}';
    await showDialog<void>(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: const Text('Share movie'),
        content: SingleChildScrollView(child: SelectableText(text)),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(dialogContext),
            child: const Text('Close'),
          ),
          FilledButton.icon(
            icon: const Icon(Icons.copy),
            label: const Text('Copy details'),
            onPressed: () async {
              try {
                await Clipboard.setData(ClipboardData(text: text));
                if (!dialogContext.mounted) return;
                Navigator.pop(dialogContext);
                if (context.mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(
                      content: Text('Movie details copied to clipboard.'),
                    ),
                  );
                }
              } catch (_) {
                if (context.mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(
                      content: Text(
                        'Could not copy. Select the text to copy it manually.',
                      ),
                    ),
                  );
                }
              }
            },
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Movie details')),
      body: SafeArea(
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 900),
            child: ListView(
              padding: const EdgeInsets.only(bottom: 24),
              children: [
                // A gradient keeps the foreground poster and metadata readable.
                SizedBox(
                  height: 280,
                  child: Stack(
                    fit: StackFit.expand,
                    children: [
                      MoviePoster(movie: movie),
                      const DecoratedBox(
                        decoration: BoxDecoration(
                          gradient: LinearGradient(
                            begin: Alignment.topCenter,
                            end: Alignment.bottomCenter,
                            colors: [Color(0x55202030), Color(0xFF10131B)],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 24,
                        bottom: 20,
                        child: SizedBox(
                          width: 136,
                          height: 204,
                          child: MoviePoster(movie: movie, hero: true),
                        ),
                      ),
                    ],
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 24),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        movie.title,
                        style: Theme.of(context).textTheme.headlineLarge
                            ?.copyWith(fontWeight: FontWeight.bold),
                      ),
                      const SizedBox(height: 8),
                      Text('${movie.year} · ${movie.runtime}'),
                      const SizedBox(height: 8),
                      Chip(
                        avatar: const Icon(Icons.star, size: 18),
                        label: Text('${movie.rating} / 10'),
                      ),
                      const SizedBox(height: 12),
                      Wrap(
                        spacing: 8,
                        runSpacing: 4,
                        children: movie.genres
                            .map((genre) => Chip(label: Text(genre)))
                            .toList(),
                      ),
                      const SizedBox(height: 20),
                      AnimatedBuilder(
                        animation: library,
                        builder: (context, _) {
                          final favorite = library.isFavorite(movie.id);
                          final rating = library.ratingFor(movie.id);
                          return Wrap(
                            spacing: 12,
                            runSpacing: 12,
                            children: [
                              FilledButton.tonalIcon(
                                key: const ValueKey('favorite-action'),
                                onPressed: () =>
                                    library.toggleFavorite(movie.id),
                                icon: Icon(
                                  favorite
                                      ? Icons.favorite
                                      : Icons.favorite_border,
                                ),
                                label: Text(
                                  favorite ? 'Favorited' : 'Favorite',
                                ),
                              ),
                              OutlinedButton.icon(
                                onPressed: () => _rateMovie(context),
                                icon: const Icon(Icons.star_outline),
                                label: Text(
                                  rating == null
                                      ? 'Rate'
                                      : 'Your rating: $rating/10',
                                ),
                              ),
                              OutlinedButton.icon(
                                onPressed: () => _shareMovie(context),
                                icon: const Icon(Icons.share_outlined),
                                label: const Text('Share'),
                              ),
                            ],
                          );
                        },
                      ),
                      const SizedBox(height: 28),
                      Text(
                        'Overview',
                        style: Theme.of(context).textTheme.titleLarge,
                      ),
                      const SizedBox(height: 10),
                      Text(movie.overview, style: const TextStyle(height: 1.6)),
                      const SizedBox(height: 28),
                      Text(
                        'Trailers',
                        style: Theme.of(context).textTheme.titleLarge,
                      ),
                      const SizedBox(height: 4),
                      const Text(
                        'Sample trailer information',
                        style: TextStyle(color: Colors.white60),
                      ),
                      const SizedBox(height: 12),
                      ListView.builder(
                        shrinkWrap: true,
                        physics: const NeverScrollableScrollPhysics(),
                        itemCount: movie.trailers.length,
                        itemBuilder: (context, index) {
                          final trailer = movie.trailers[index];
                          return Card(
                            margin: const EdgeInsets.only(bottom: 10),
                            child: ListTile(
                              contentPadding: const EdgeInsets.all(12),
                              leading: const Icon(
                                Icons.movie_outlined,
                                size: 30,
                              ),
                              title: Text(trailer.title),
                              subtitle: Text(
                                '${trailer.duration} · ${trailer.description}',
                              ),
                            ),
                          );
                        },
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

// Source: lib/screens/home.dart

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});
  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  final _library = MovieLibrary();
  final _search = TextEditingController();
  String _query = '';
  bool _favoritesOnly = false;

  @override
  void dispose() {
    _library.dispose();
    _search.dispose();
    super.dispose();
  }

  void _openMovie(Movie movie) {
    // Pass the selected Movie object to the new route.
    Navigator.push<void>(
      context,
      MaterialPageRoute<void>(
        builder: (_) => MovieDetailScreen(movie: movie, library: _library),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: const Icon(Icons.movie_filter_outlined),
        title: const Text('Movie Explorer'),
      ),
      body: SafeArea(
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 900),
            child: AnimatedBuilder(
              animation: _library,
              builder: (context, _) {
                final movies = sampleMovies.where((movie) {
                  final matches = '${movie.title} ${movie.genres.join(' ')}'
                      .toLowerCase()
                      .contains(_query);
                  return matches &&
                      (!_favoritesOnly || _library.isFavorite(movie.id));
                }).toList();
                // Header and cards scroll together, including in landscape.
                return ListView.builder(
                  padding: const EdgeInsets.fromLTRB(20, 16, 20, 24),
                  itemCount: movies.length + 2,
                  itemBuilder: (context, index) {
                    if (index == 0) {
                      return Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Find your next story.',
                            style: Theme.of(context).textTheme.headlineMedium
                                ?.copyWith(fontWeight: FontWeight.bold),
                          ),
                          const SizedBox(height: 8),
                          const Text(
                            'Three unforgettable journeys. Pick a movie to explore.',
                          ),
                          const SizedBox(height: 24),
                          TextField(
                            controller: _search,
                            onChanged: (value) => setState(
                              () => _query = value.trim().toLowerCase(),
                            ),
                            decoration: InputDecoration(
                              hintText: 'Search movies or genres',
                              prefixIcon: const Icon(Icons.search),
                              suffixIcon: _query.isEmpty
                                  ? null
                                  : IconButton(
                                      tooltip: 'Clear search',
                                      icon: const Icon(Icons.close),
                                      onPressed: () {
                                        _search.clear();
                                        setState(() => _query = '');
                                      },
                                    ),
                            ),
                          ),
                          const SizedBox(height: 16),
                          Wrap(
                            spacing: 10,
                            runSpacing: 8,
                            children: [
                              ChoiceChip(
                                label: const Text('All movies'),
                                selected: !_favoritesOnly,
                                onSelected: (_) =>
                                    setState(() => _favoritesOnly = false),
                              ),
                              ChoiceChip(
                                label: Text(
                                  'Favorites (${_library.favoriteCount})',
                                ),
                                selected: _favoritesOnly,
                                onSelected: (_) =>
                                    setState(() => _favoritesOnly = true),
                              ),
                            ],
                          ),
                          const SizedBox(height: 20),
                        ],
                      );
                    }
                    if (index == movies.length + 1) {
                      return Padding(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        child: Text(
                          movies.isEmpty
                              ? 'No movies found. Try another search or switch to All movies.'
                              : '${movies.length} movies · Select a card to view details',
                          textAlign: TextAlign.center,
                        ),
                      );
                    }
                    final movie = movies[index - 1];
                    return Card(
                      margin: const EdgeInsets.only(bottom: 14),
                      clipBehavior: Clip.antiAlias,
                      child: InkWell(
                        key: ValueKey('movie-${movie.id}'),
                        onTap: () => _openMovie(movie),
                        child: Padding(
                          padding: const EdgeInsets.all(14),
                          child: Row(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              SizedBox(
                                width: 88,
                                height: 132,
                                child: MoviePoster(movie: movie, hero: true),
                              ),
                              const SizedBox(width: 16),
                              Expanded(
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(
                                      movie.title,
                                      style: Theme.of(context)
                                          .textTheme
                                          .titleLarge
                                          ?.copyWith(
                                            fontWeight: FontWeight.bold,
                                          ),
                                    ),
                                    const SizedBox(height: 8),
                                    Text('${movie.year} · ${movie.runtime}'),
                                    const SizedBox(height: 6),
                                    Text(
                                      movie.genres.join(' / '),
                                      style: Theme.of(context)
                                          .textTheme
                                          .bodySmall,
                                    ),
                                    const SizedBox(height: 10),
                                    Wrap(
                                      spacing: 12,
                                      runSpacing: 8,
                                      crossAxisAlignment:
                                          WrapCrossAlignment.center,
                                      children: [
                                        Text(
                                          '★ ${movie.rating.toStringAsFixed(1)} / 10',
                                          style: TextStyle(
                                            color: Theme.of(context)
                                                .colorScheme
                                                .primary,
                                          ),
                                        ),
                                        if (_library.isFavorite(movie.id))
                                          const Icon(
                                            Icons.favorite,
                                            color: Colors.pinkAccent,
                                            size: 20,
                                          ),
                                        if (_library.ratingFor(movie.id) !=
                                            null)
                                          Text(
                                            'You: ${_library.ratingFor(movie.id)}/10',
                                          ),
                                      ],
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    );
                  },
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}

// Source: lib/main.dart

void main() => runApp(const MovieApp());

class MovieApp extends StatelessWidget {
  const MovieApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'LAB 5 - Movie Explorer',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xFF10131B),
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFFFB45B),
          brightness: Brightness.dark,
          primary: const Color(0xFFFFB45B),
          surface: const Color(0xFF1B202C),
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF10131B),
          centerTitle: false,
        ),
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: BorderSide.none,
          ),
        ),
      ),
      home: const HomeScreen(),
    );
  }
}
