// Generated by tools/update_dartpad.ps1. Edit lib/ and regenerate this file.
import 'package:flutter/material.dart';

// Source: lib/data/movie_data.dart
class Movie {
  const Movie({
    required this.title,
    required this.year,
    required this.genres,
    required this.posterUrl,
    required this.rating,
  });

  final String title;
  final int year;
  final List<String> genres;
  final String posterUrl;
  final double rating;
}

const allMovies = <Movie>[
  Movie(
    title: 'Zootopia 2',
    year: 2025,
    genres: ['Adventure', 'Animation', 'Comedy'],
    posterUrl: 'https://picsum.photos/seed/zootopia-2/300/450',
    rating: 7.3,
  ),

  Movie(
    title: 'KPop Demon Hunters',
    year: 2025,
    genres: ['Animation', 'Action', 'Adventure', 'Comedy'],
    posterUrl: 'https://picsum.photos/seed/kpop-demon-hunters/300/450',
    rating: 7.4,
  ),

  Movie(
    title: 'Elio',
    year: 2025,
    genres: ['Animation', 'Action', 'Adventure', 'Comedy', 'Sci-Fi'],
    posterUrl: 'https://picsum.photos/seed/elio-2025/300/450',
    rating: 6.6,
  ),

  Movie(
    title: 'Superman',
    year: 2025,
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    posterUrl: 'https://picsum.photos/seed/superman-2025/300/450',
    rating: 7.0,
  ),

  Movie(
    title: 'F1: The Movie',
    year: 2025,
    genres: ['Action', 'Drama', 'Sport'],
    posterUrl: 'https://picsum.photos/seed/f1-the-movie/300/450',
    rating: 7.6,
  ),

  Movie(
    title: 'Weapons',
    year: 2025,
    genres: ['Drama', 'Horror', 'Mystery'],
    posterUrl: 'https://picsum.photos/seed/weapons-2025/300/450',
    rating: 7.4,
  ),
];

// Source: lib/data/genre_data.dart
const genreData = <String>[
  'Action',
  'Adventure',
  'Animation',
  'Comedy',
  'Drama',
  'Romance',
  'Sci-Fi',
  'Thriller',
];

// Source: lib/screens/genre_screen.dart

enum MovieSort {
  aToZ('A-Z'),
  zToA('Z-A'),
  year('Year'),
  rating('Rating');

  const MovieSort(this.label);

  final String label;
}

class GenreScreen extends StatefulWidget {
  const GenreScreen({super.key});

  @override
  State<GenreScreen> createState() => _GenreScreenState();
}

class _GenreScreenState extends State<GenreScreen> {
  final TextEditingController _searchController = TextEditingController();
  String _searchQuery = '';
  final List<String> _selectedGenres = [];
  MovieSort _selectedSort = MovieSort.aToZ;

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  void _clearFilters() {
    _searchController.clear();
    setState(() {
      _searchQuery = '';
      _selectedGenres.clear();
      _selectedSort = MovieSort.aToZ;
    });
  }

  @override
  Widget build(BuildContext context) {
    // Lọc phim theo tên và thể loại.
    final keyword = _searchQuery.trim().toLowerCase();
    final displayedMovies = allMovies.where((movie) {
      final matchKeyword = movie.title.toLowerCase().contains(keyword);
      final matchGenre =
          _selectedGenres.isEmpty ||
          movie.genres.any((genre) => _selectedGenres.contains(genre));
      return matchKeyword && matchGenre;
    }).toList();

    // Sắp xếp danh sách đã lọc.
    displayedMovies.sort((a, b) {
      switch (_selectedSort) {
        case MovieSort.aToZ:
          return a.title.compareTo(b.title);
        case MovieSort.zToA:
          return b.title.compareTo(a.title);
        case MovieSort.year:
          return b.year.compareTo(a.year);
        case MovieSort.rating:
          return b.rating.compareTo(a.rating);
      }
    });

    return Scaffold(
      appBar: AppBar(title: const Text('LAB6 - Movie Browser')),
      body: SafeArea(
        child: LayoutBuilder(
          builder: (context, constraints) {
            final isWide = constraints.maxWidth >= 800;
            double textScale = MediaQuery.textScalerOf(context).scale(1);
            if (textScale < 1) {
              textScale = 1;
            }

            return ListView(
              padding: const EdgeInsets.all(16),
              children: [
                const Text(
                  'Find a Movie',
                  style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 16),

                // Tìm kiếm.
                TextField(
                  controller: _searchController,
                  decoration: const InputDecoration(
                    hintText: 'Search movies',
                    prefixIcon: Icon(Icons.search),
                    border: OutlineInputBorder(),
                  ),
                  onChanged: (value) {
                    setState(() {
                      _searchQuery = value;
                    });
                  },
                ),
                const SizedBox(height: 16),

                // Chọn thể loại.
                Text('Genres (${_selectedGenres.length} selected)'),
                const SizedBox(height: 8),
                Wrap(
                  spacing: 8,
                  runSpacing: 8,
                  children: genreData.map((genre) {
                    return FilterChip(
                      label: Text(genre),
                      selected: _selectedGenres.contains(genre),
                      onSelected: (selected) {
                        setState(() {
                          if (selected) {
                            _selectedGenres.add(genre);
                          } else {
                            _selectedGenres.remove(genre);
                          }
                        });
                      },
                    );
                  }).toList(),
                ),
                const SizedBox(height: 16),

                // Sắp xếp và xóa bộ lọc.
                Wrap(
                  spacing: 16,
                  runSpacing: 8,
                  crossAxisAlignment: WrapCrossAlignment.center,
                  children: [
                    Text('${displayedMovies.length} movies found'),
                    const Text('Sort by:'),
                    DropdownButton<MovieSort>(
                      value: _selectedSort,
                      items: MovieSort.values.map((sort) {
                        return DropdownMenuItem(
                          value: sort,
                          child: Text(sort.label),
                        );
                      }).toList(),
                      onChanged: (value) {
                        if (value != null) {
                          setState(() {
                            _selectedSort = value;
                          });
                        }
                      },
                    ),
                    TextButton(
                      onPressed: _clearFilters,
                      child: const Text('Clear filters'),
                    ),
                  ],
                ),
                const SizedBox(height: 20),

                // Màn hình rộng: hai cột. Màn hình hẹp: một cột.
                if (displayedMovies.isEmpty)
                  const Center(child: Text('No movies found.'))
                else if (isWide)
                  GridView.count(
                    crossAxisCount: 2,
                    crossAxisSpacing: 12,
                    mainAxisSpacing: 12,
                    mainAxisExtent: 220 * textScale,
                    shrinkWrap: true,
                    physics: const NeverScrollableScrollPhysics(),
                    children: displayedMovies.map((movie) {
                      return _buildMovieCard(movie);
                    }).toList(),
                  )
                else
                  ...displayedMovies.map((movie) => _buildMovieCard(movie)),
              ],
            );
          },
        ),
      ),
    );
  }

  Widget _buildMovieCard(Movie movie) {
    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SizedBox(
              width: 80,
              height: 120,
              child: Image.network(
                movie.posterUrl,
                fit: BoxFit.cover,
                errorBuilder: (context, error, stackTrace) {
                  return const Icon(Icons.movie, size: 40);
                },
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    movie.title,
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                    style: const TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text('Year: ${movie.year}'),
                  const SizedBox(height: 8),
                  Text(
                    movie.genres.join(' / '),
                    maxLines: 3,
                    overflow: TextOverflow.ellipsis,
                  ),
                  const SizedBox(height: 8),
                  Text('Rating: ${movie.rating}/10'),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// Source: lib/main.dart

void main() {
  runApp(const ResponsiveMovieApp());
}

class ResponsiveMovieApp extends StatelessWidget {
  const ResponsiveMovieApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Lab 6 – Building a Responsive Movie Genre Browsing Screen',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const GenreScreen(),
    );
  }
}
